### ISSUE TITLE
Installer?

### ISSUE THREAD

**Issue by Fluxanode** [Koromix/tytools#105]
Is there a windows exe and installer for the tools and monitor?

**Comment by Defragster** [comment]
Yes, See here: https://github.com/Koromix/tytools/releases

Though in years of use here - only the unzip to a folder and running from there has been used to great effect.
May require UNBLOCK of the .exe's for use.

Recent issue found some issue with the installer by another user.

**Comment by Koromix** [comment]
There is, in the release section, as pointer out above by Defragster ;)
https://github.com/Koromix/tytools/releases
