### ISSUE TITLE
Generic has No Serial Log

### ISSUE THREAD

**Issue by Defragster** [Koromix/tytools#16]
Current version 8-146 has NO serial log available:
![generic_tycom_8-146](https://cloud.githubusercontent.com/assets/8165609/25784493/ce8d14ec-3322-11e7-9508-9c38c8b57007.png)

**Comment by Koromix** [comment]
This is already covered by #10, specifically point 3. I'll post details about it there.

**Comment by Defragster** [comment]
Okay - it was working before - it was a regression, glad it is back

**Comment by Koromix** [comment]
Sorry for closing this issue so quickly. Actually it was not supposed to work before: the serial log is disabled when the UNIQUE flag is not set. This means the log worked by accident.

**Comment by Defragster** [comment]
No problem - glad it worked before or I would have complained more :)

Thanks for the fixes and changes!  I just pulled down 0.8.0-160 and I can name my devices now!
