### ISSUE TITLE
TyTools 0.8.6 - error/unable to program a HEX file in Linux for Teensy 3.2

### ISSUE THREAD

**Issue by pramilo** [Koromix/tytools#19]
Hi

I am using Teensy 3.2 and have downloaded and compiled TyTools 0.8.6 under Ubuntu 16.

Whenever I try to upload a file I get the error "Firmware .... is only compatible with Teensy 3.1 and 3.2"
However I do have a Teensy 3.2 connected! So it should allow the programming.

From looking at the GUI it seems the board is being recognized as "Teensy" only. I attach a screenshot of the issue.

I tested programming the board using Windows 7 and a much older version (TyQT 0.7.5) and it shows up correctly as Teensy 3.2 and allows programming using the same HEX file.

Therefore I am inclined to believe this to be a bug.

Can you please advise?

Thank you

![capture](https://user-images.githubusercontent.com/12521691/26848408-3e7effda-4af8-11e7-8c99-815329d01251.JPG)

**Comment by Koromix** [comment]
Thanks for the report, this is indeed a serious regression. Probably should have tested the changes I've made for #4 a bit more :D

This should work correctly in TyTools 0.8.7.
