### ISSUE TITLE
IHEX parse error

### ISSUE THREAD

**Issue by luni64** [Koromix/tytools#21]
_Windows 10, TyTCommander Version 0.8.8_

I get the following parse error for the attached hex file.  

![parse error](https://user-images.githubusercontent.com/12611497/31141300-476ef06e-a877-11e7-8afe-212dd2cf2857.PNG)

Uploading the corresponding .elf file (attached) works however.  Teensy.exe uploads the hex without problems.  I also recompiled, added changes to the code, rebooted computer... The error seems to be quite stable. Other hex files work as usual. 

[usbhost.zip](https://github.com/Koromix/tytools/files/1353376/usbhost.zip)

**Comment by luni64** [comment]
I just had a look at the hex file. Line 2755 is at the end of the file. Looks like you are stumbling over the 05 Record (Start Linear Address). I have no idea why objcopy adds this record in this case and not in all others.  

Here a corresponding SO question:  [https://stackoverflow.com/questions/26295776/what-are-the-intel-hex-records-type-03-or-05-doing-in-ihex-program-for-arm
](https://stackoverflow.com/questions/26295776/what-are-the-intel-hex-records-type-03-or-05-doing-in-ihex-program-for-arm
)

**Comment by Koromix** [comment]
Thanks for reporting this bug,

I've pushed a commit to fix this issue. Development build *TyTools-0.8.8-7-g0c123c2* on [BinTray](https://bintray.com/koromix/tytools/tytools/view#files) should work correctly.

**Comment by luni64** [comment]
Works, 
Thanks for fixing
