### ISSUE TITLE
Option to upload value of HEX

### ISSUE THREAD

**Issue by varadig** [Koromix/tytools#23]
Is there option to upload value of HEX file instead of give the path of the hex file to the tycmd?

**Comment by Koromix** [comment]
Hi, and sorry for the delay.

I've added the possibility of uploading from stdin in the latest build, I don't know if that answers your need?
It only works with Intel HEX (*.hex) files.
You can find development builds on my BinTray account: [https://bintray.com/koromix/tytools/tytools/view/files#files/](https://bintray.com/koromix/tytools/tytools/view/files#files/) (right now it's TyTools-0.8.8-16-g396b7b9)

To do so, use "tycmd upload -f ihex -" and the firmware will be read from standard input.
