### ISSUE TITLE
TD 1.42 Beta 5

### ISSUE THREAD

**Issue by Defragster** [Koromix/tytools#27]
PJRC released 1.42 beta 5 - with correction for the T_3.5.  Also this addition might be useful for TyCommander - hopefully it won't break anything … downloaded but not installed/tested.

"This beta puts info about which chip was used in the USB BCD version number, so the Ports menu can show which Teensy you're using even if it hasn't yet seen the board go into bootloader mode."

Also added : https://forum.pjrc.com/threads/52315-Teensyduino-1-42-Beta-5?p=179367&viewfull=1#post179367

**Comment by Koromix** [comment]
Hi,

This is now supported in TyTools 0.8.10.
Only small gotcha is that Teensy 3.2 may show up as Teensy 3.1 (the version info from the bcdDevice field is the same for 3.1 and 3.2) until a reboot happens, and the bootloader gives better information (3.2).

TyCommander still uses a cache to remember version information for each board, using the serial number.
