### ISSUE TITLE
Teensy 3.5 Compatibility

### ISSUE THREAD

**Issue by arduinodavid** [Koromix/tytools#28]
I'm trying to load some code built for Teensy 3.5 into a Teensy 3.5, but tyCommander is saying it is compatible only with Teensy 3.1 and 3.2. Teensy loader does it just fine.

Is there something I need to set?

**Comment by arduinodavid** [comment]
PS Using 0.8.8-25-gd93a283

**Comment by Koromix** [comment]
Hi,

This bug is fixed in development builds, you can find them on BinTray: https://bintray.com/koromix/tytools/tytools/view#files
The latest build is: TyTools-0.8.8-25-gd93a283
