### ISSUE TITLE
Add compilation using Teensy builder

### ISSUE THREAD

**Issue by FrankBoesing** [Koromix/tytools#35]
Hi, if you'd add compilation for projects using the teensy builder (look @ 2. line of output of Arduino-window - very easy!), your tools would be really complete!

One could use any editor and use your tytools to compile&upload the projects.

It would need some menues to choose the teensy-model, speed ..etc - perhaps it could store the stettings in the project directory?

**Comment by Defragster** [comment]
It is overkill - but @luni with the VisualTeensy created a setup settings interface - it then creates a full makefile that isn't needed.  Maybe there could be a merging?
