### ISSUE TITLE
What is the real current version?

### ISSUE THREAD

**Issue by systronix** [Koromix/tytools#37]
Thanks again for a great program! I have been using it steadily for the last two years with (at the lab) multiple Teensy 3.2 connected, running 24/7 stress tests. I'm using on WIndows 10 and Ubuntu and a customer is also using it at their manufacturing facility to load code onto systems in the final mfg steps. So recently I updated their systems to 0.8.10 using the Win64 msi, and the exe reports 0.8.10.

Then on Linux I built from Git source after a fresh master pull, which has the Sep 23 comment about version as 0.8.10 but TyCommander and tycmd say 0.8.8-33-g5c39966, so how do I get 0.8.10?

**Comment by Koromix** [comment]
This also probably means I  need to switch to annotated tags next time...
