### ISSUE TITLE
Baudrate for USB Serial Cables

### ISSUE THREAD

**Issue by luni64** [Koromix/tytools#43]
In cases where I can not use the native Teensy USB Serial (e.g. when I use it to communicate to a PC program) I usually connect a FTDI USB-Serial cable to Serial1 for debugging. 
Since tyCmd is able to connect to the FTDI I would like to use its serial monitor for debugging. 

However, it looks like it doesn't detect the baud rate correctly. 

![image](https://user-images.githubusercontent.com/12611497/68143878-aef12e00-ff32-11e9-8b29-86fac7a1f060.png)

After I connect the cable to putty, set the correct baudrate and quit putty,  it works in tyCmd as well:

![image](https://user-images.githubusercontent.com/12611497/68144027-07c0c680-ff33-11e9-851f-5ccfa3ad0e5e.png)

Any chance to add  baudrate setting / autodetect to generic boards?

**Comment by Koromix** [comment]
In the latest commit, I've added a per-board serial rate setting available in the "Options" tab. Like other settings, TyTools remembers it.
I haven't tested it with a non-Teensy board but it should work the same.

You can find the corresponding Win64 build here: https://koromix.dev/files/tytools/

**Comment by luni64** [comment]
Thanks, this kind of works. Changing the baudrate to the correct value only works after power cycling (plug out/in) of the usb cable. Looks like it doesn't apply the baudrate immediately but stores the value and sets it at detection of the device. Same for setting to a wrong baudrate.

**Comment by Koromix** [comment]
OK, what about the new-new-build? :p
https://koromix.dev/files/tytools/

**Comment by luni64** [comment]
Did you change anything? It has the same build number as the one I tested

**Comment by luni64** [comment]
Sorry, didn't refresh the browser....

**Comment by luni64** [comment]
Perfect, switching baud rates works now. 

However, I get some additional blank lines in the output. (not a big deal but putty doesn't show them). Seems to work if I use the native Serial port instead Serial1 + cable.  This has nothing to do with the current changes, I observed them for quite while. 

![image](https://user-images.githubusercontent.com/12611497/69884505-03d95780-12d9-11ea-9d11-5dd59a3a0e9c.png)

Code: 
![image](https://user-images.githubusercontent.com/12611497/69884564-531f8800-12d9-11ea-8564-1b96b5c5dcf0.png)

**Comment by Koromix** [comment]
Hmmm, I may have an idea about that.
I just need to find my own USB-serial converter to do some tests (which may be the hardest part about it).

**Comment by Koromix** [comment]
Does the new build (TyTools-0.8.11-16-gc874426) fix the extra-lines issue ?
I could not test it (still haven't found my converter), so it's based on a hunch.

**Comment by luni64** [comment]
Yes, works perfectly. 
Thanks again, this tool gets better and better all the time!  :-)

**Comment by Koromix** [comment]
Thanks for the test!
