### ISSUE TITLE
Teensy USB recognition

### ISSUE THREAD

**Issue by ttlappalainen** [Koromix/tytools#44]
Hi,

Do you have simple description how I could recognize some USB port as Teensy port and get its serial number as you have? I need that in my delphi application.

Timo

**Comment by Koromix** [comment]
You could use the command-line version (tycmd, it does not depend on Qt) like this: `tycmd list -v -Ojson`. It's free, just package it in your application, call it and parse the JSON result.

If you want to do it yourself, you need to list USB serial and HID devices. This is platform-specific, and can be annoying. There are libraries, though I don't know exactly what you should use, especially in a Delphi application.
