### ISSUE TITLE
Trying to setup tytools

### ISSUE THREAD

**Issue by amralabsi** [Koromix/tytools#51]
I am having an issue trying to setup tytools because I need to use tycmd monitor, so I am doing the steps in hacking TyTools and using a mac I do the static Qt build after that's done I make install and everything goes fine with the qt build but then when I try to do cmake ../.. the follow:

amrs-mbp:darwin MiamoorZ$ cmake ../..
CMake Error at lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file

     "/Users/MiamoorZ/tytools/lib/qt5/x86_64-darwin-clang/../../../Users/MiamoorZ/tytools/lib/qt5/x86_64-darwin-clang//mkspecs/macx-clang"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/Users/MiamoorZ/tytools/lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:50 (_qt5_Core_check_file_exists)
  lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:172 (include)
  lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:88 (find_package)
  lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:88 (find_package)
  lib/qt5/x86_64-darwin-clang/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  cmake/FindEasyQt5.cmake:50 (find_package)
  src/tycommander/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/MiamoorZ/tytools/build/darwin/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/Koromix/tytools/files/4264847/CMakeOutput.log)

**Comment by Koromix** [comment]
Hi,

It is a bug in the Qt build tool which I've noticed too. I need to document it. Static builds are not encouraged by Qt and there are all sorts of bugs and weird stuff when tryong to do it.

In the folder where you extratcted (and built) Qt, you need to find and change the file that contains this path: "/Users/MiamoorZ/tytools/lib/qt5/x86_64-darwin-clang/../../../Users/MiamoorZ/tytools/lib/qt5/x86_64-darwin-clang//mkspecs/macx-clang" and replace the path with "/Users/MiamoorZ/tytools/lib/qt5/x86_64-darwin-clang/mkspecs/macx-clang".

After that it should work.
