### ISSUE TITLE
Teensy :: _teensy_model_identifier

### ISSUE THREAD

**Issue by Defragster** [Koromix/tytools#52]
I just discovered that the .ld files posted for Teensy include the _teensy_model_identifier used to identify what Teensy is connected?

For T_4.0: T:\arduino-1.8.12\hardware\teensy\avr\cores\teensy4\imxrt1062.ld
_teensy_model_identifier = 0x24;

For unreleased T_4.1: T:\arduino-1.8.12\hardware\teensy\avr\cores\teensy4\imxrt1062_t41.ld
_teensy_model_identifier = 0x25;

If TyTools could recognize { for Serial connect only until after release } it would be properly identified and handled for Serial Monitoring when the T_4.1 releases.

**Comment by KurtE** [comment]
@Defragster @Koromix - I think I have a version that will probably work when T4.1 is released. 

It is based off of your multi stream branch:
https://github.com/KurtE/tytools/tree/T4_1_MS

I could do a PR, but may want to wait until we can fully verify it works when the T4.1 is released

**Comment by Koromix** [comment]
Merged it, thanks!
Windows builds for master and multiple_serials branches can be found here: https://koromix.dev/files/tytools/

**Comment by Koromix** [comment]
Windows builds for master and multiple_serials branches can be found here: https://koromix.dev/files/tytools/
