### ISSUE TITLE
Post update Release binaries for T_4.1

### ISSUE THREAD

**Issue by Defragster** [Koromix/tytools#57]
Don't see an update on the Releases page for latest build?

**Comment by Koromix** [comment]
Done!
Without the multiple serials stuff though.

**Comment by Defragster** [comment]
Thanks, though multiple serial seems to work with prior intermediate build.

Only odd thing I saw was sometime I was getting multiple restarts?  Though it was using the GDB debugger - so maybe it was that I wondered but never tested.
