### ISSUE TITLE
I/O error on upload with TyCommander

### ISSUE THREAD

**Issue by MikeMaurice** [Koromix/tytools#62]
I have traced this down to a probable issue with a USB 3.0 serial port, or the cable which may not be 3.0 compatible.

**Comment by Defragster** [comment]
Is that with a Teensy 4.x?  It's High Speed USB can push limits ...

**Comment by MikeMaurice** [comment]
Yes, 4.1. Fruther testing indicates it is the 3.0 port on the windows 7 computer.

**Comment by Koromix** [comment]
Despite the error, does the Teensy actually reboot and run the new sketch or do you need to do it manually ?

**Comment by Koromix** [comment]
Closing this due to lack of information.
