### ISSUE TITLE
Issue Uploading Sketch

### ISSUE THREAD

**Issue by ChrispyChris** [Koromix/tytools#71]
I see that it says I can use this to upload sketches aside from just firmware, so I figured I would give it a shot. I've got my Teensy 4.1 plugged in, tyupdater running, and it even appears I'm able to reset the board through the software, but when I tried to upload a sketch it was telling me that it didn't recognize the extension. Is there something I need to do on top of just writing the code for tyupdater to be able to load my program on the Teensy 4.1?

I'm running Arch Linux, and I just pulled the repository today and built it.

I apologize if this isn't the best place to ask this, I just didn't know where else to ask.

**Comment by Defragster** [comment]
Only HEX files are uploaded - built from sketches or other source files when not from within the Arduino IDE.

Tytools doesn't build HEX files or deal with source code - but when supplied a valid HEX can upload it to a Teensy over USB.
