### ISSUE TITLE
tycommander.exe failing after build Win10

### ISSUE THREAD

**Issue by makeller1** [Koromix/tytools#74]
I followed the instructions to install the 32 bit version on windows 10, got to the point where I could open the solution TyTools.sln, and built "ALL_BUILD" and received a lot of link2038 errors:

... e.g.
>Qt5Widgets.lib(qinputdialog.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in mocs_compilation.obj
...
>F:\CppLearning\tytools\build\win32\Debug\TyCommander.exe : fatal error LNK1319: 1250 mismatches detected

I followed the readme in the qt5 directory and installed Qt 5.12.10. One thing I did that wasn't explicitly written in the directions was during the Qt install, I ran "nmake install". 

Any idea what could be the problem?

**Comment by Koromix** [comment]
Oops, sorry I did not reply in time.

Did you build Qt yourself (with the static Qt instructions?)
If so, this build does not work in debug mode. Use RelWithDebInfo to build TyTools.
The handling of static Qt is a bit of a mess.. Hopefully they make it better in Qt6.
