### ISSUE TITLE
Couldn't upload firmware

### ISSUE THREAD

**Issue by lavanthaya** [Koromix/tytools#78]
Hi,

I am trying to use tytools from the Ubuntu machine to upload firmware to the teensy board (3.2),
But it's not happening.
With tytools, I can list connected devices, can monitor but upload and reset is not working,
I'm getting below error,

![image](https://user-images.githubusercontent.com/46497911/123156824-55f64680-d444-11eb-9290-07283b5837af.png)

Can anyone please help me with this?
Note:I am running an ubuntu machine on a VMware workstation (VM).

**Comment by Koromix** [comment]
Which version ot TyTools are you using?
Type `tycmd --version` to check.

**Comment by lavanthaya** [comment]
My version is,
tycmd 0.9.3-7-g766531b

**Comment by Koromix** [comment]
Did you follow the Linux instructions to setup udev correctly?
You can find them here: https://www.pjrc.com/teensy/td_download.html (__Linux installation__ part)

**Comment by lavanthaya** [comment]
Yes, I followed the same instruction to install teensy,
As I mentioned above, I can use tycmd command with "list" or "monitor", only the "upload" or "reset" commands are not working

**Comment by Koromix** [comment]
I just noticed the use of VMWare.

When a Teensy is programmed, the device disappears and then reappears. If you don't automatically (or quickly) ressasign it to the VM, it looks like it is gone from inside the VM.

I think that explains the problem you are seeing. I'm closing this issue for this reason, feel free to reopen if I'm mistaken.
