### ISSUE TITLE
TyQT uses wrong name for upload file

### ISSUE THREAD

**Issue by mfratus2001** [Koromix/tytools#8]
Using Linux Mint most recent version. Ty looking for filename:
/home/ralph/ty-master/build/linux/tyqt upload --autostart --wait --multi /tmp/arduino_build_648198/effects-12.25d.ino.TEENSY31.hex
But Teensy compiler iDE makes:
/home/ralph/ty-master/build/linux/tyqt upload --autostart --wait --multi /tmp/arduino_build_648198/effects-12.25d.ino.hex
It worked one time, but now does not. How do you de-integrate this from Arduino and Teensy IDE?

**Comment by Koromix** [comment]
Better later than never... Sorry about that.

When TyQt integrates to the IDE it changes the build instructions a bit to generate both "effects-12.25d.ino.hex" and "effects-12.25d.ino.TEENSY31.hex", so this name is valid.

You can de-integrate TyQt with the integration tool in "Tools > Integrate to Arduino". Set the arduino path and click "Restore".
