### ISSUE TITLE
Teensy not found on Ubuntu 21.10, Raspberry Pi 4

### ISSUE THREAD

**Issue by mr-j-tree** [Koromix/tytools#81]
Hello!

I have a Teensy 4.1 connected via USB to a Raspberry Pi 4 which is running Ubuntu Desktop 21.10. The system can see the Teensy at the USB level - running `lsusb` returns the following entry for the Teensy:

> Bus 001 Device 013: ID 16c0:0483 Van Ooijen Technische Informatica Teensyduino Serial

`tycmd` however cannot see the Teensy. Running `tycmd list` returns an empty result. I have built tytools v0.9.4 per the instructions, and it builds cleanly with no errors showing. The `tycommander` GUI runs on this system without errors but also shows no boards connected.

For reference, I can see the same Teensy using `tycmd` and `tycommander` when connected to my macOS machine, using the same v0.9.4 release, the same running Teensy sketch and the same USB cables.

I'm wondering if you have ever successfully used tycmd on Raspberry Pi 4? Or are there any special considerations to get it to be able to see the attached device(s)?

Thanks!

_Josh_

**Comment by Koromix** [comment]
Ok I've got a working install of Ubuntu 21.10 on my Raspberry Pi 400, which took longer than because of this painful bug: [https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1946368](https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1946368)...

I can confirm that it does not work correctly.
I will work on it in the newxt few days and report to you.

**Comment by Koromix** [comment]
Okay found the problem, and it does not come from TyTools.

Some drivers (such as _drivers/usb/class/cdc-acm_ which is needed to handle USB serial with Teensy) have been moved to an extra package: __linux-modules-extra-raspi__

I'll try to add some kind of warning in TyCommander to help users. In the mean time, just install this package, unplug and replug your Teensy, and it should solve your problem :)

**Comment by Koromix** [comment]
You can find more information about this change here: https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1947723

**Comment by mr-j-tree** [comment]
Many thanks!!!
