### ISSUE TITLE
TyCommander fails to release the com port

### ISSUE THREAD

**Issue by MikeMaurice** [Koromix/tytools#90]
Unlike the teensy loader, TyCommander 0 97  does not release the com port after loading. 
Since, TyC seems to be using the teensy loader to do the actual load, maybe there is something I am missing. Complicates debugging on the cmd window as TyCmd monitor won't open the com port until
TyCommander is closed.
Any thoughts?

**Comment by luni64** [comment]
You can enable/disable the Serial connection of TyCommander by clicking on the Serial button:

![image](https://user-images.githubusercontent.com/12611497/157601407-e0d8eb10-2bda-44e7-9047-1701617c2520.png)

Also in Tools | Preferences you can choose to not start the Serial connection by default. 

![image](https://user-images.githubusercontent.com/12611497/157601558-87aae1d0-dfe7-4f77-b57a-9ca9be224ac3.png)

Hope that helps
