### ISSUE TITLE
can't be installed on M1 mac

### ISSUE THREAD

**Issue by adammanella** [Koromix/tytools#95]
it says the developer can't be verified and then asks if I would like to eject or cancel

**Comment by adammanella** [comment]
I just needed to right click and then click open to over ride the computer malware trust issue

**Comment by Koromix** [comment]
Indeed, I should document this, I guess.

The alternative is paying Apple Developer ID (99 USD/year IIRC) to sign release packages, which I won't do for a free and open-source software such as this.
