### ISSUE TITLE
TyUploader Doesn't detect Teensy MM in Serial+MTP mode

### ISSUE THREAD

**Issue by david-res** [Koromix/tytools#98]
I have a Teensy MicroMod set up as a Serial+MTP device, when plugged into USB, it does not appear in the device list.
If I click the boot button it appears as HalfKay
![image](https://user-images.githubusercontent.com/52652879/193229287-4658c547-8e6f-41a5-88fc-186ab4939432.png)

Is there a way to fix this?

**Comment by Defragster** [comment]
There was a fix to ID the new VID_PID this Serial+MTP creates, but it hasn't been formally released ?

**Comment by david-res** [comment]
@Defragster thanks for confirming!
What OS are you running on?
If you have a macos build I’d love to try it out.
@Koromix of you could create a new release with the fix that would be highly appreciated

**Comment by Defragster** [comment]
Sorry - I'm on Windows - so no help there.

**Comment by Koromix** [comment]
Yeah this is overdue, I don't have a Mac anymore but I'll try to make a release anyway 😁

**Comment by Koromix** [comment]
Although I do have a running Mac on QEMU for another project, so that should do :) I'll make a release today then!

**Comment by david-res** [comment]
@Koromix thanks! Very appreciated!

**Comment by Koromix** [comment]
Not home right now, so it'll have to wait until tomorrow :)

**Comment by Koromix** [comment]
I've made a release: https://github.com/Koromix/tytools/releases/tag/v0.9.8

**Comment by david-res** [comment]
All working! Thanks!!
